/* Generated by tools/syzlang_gen.py. Do not edit.
 *
 * The NV_* ioctl command numbers this campaign models, as _IOWR
 * macros for syz-extract. Numbers are derived from a checkout of
 * NVIDIA/open-gpu-kernel-modules and go stale when the branch moves;
 * regenerate with tools/ioctl_inventory.py followed by this tool.
 *
 * RM escapes use the Linux _IOC encoding with magic 'F' (0x46).
 * UVM commands do not: UVM_IOCTL_BASE(i) expands to i on Linux, so
 * a UVM number is the bare command number with no _IOC fields.
 */
#ifndef GSPWN_NVIDIA_IOCTL_H
#define GSPWN_NVIDIA_IOCTL_H

#include <linux/ioctl.h>

#define NV_IOCTL_MAGIC 0x46

/* /dev/nvidiactl, /dev/nvidiaN */
#define NV_ESC_RM_ALLOC_MEMORY                   _IOWR(NV_IOCTL_MAGIC, 39, char[56]) /* 0xc0384627 */
#define NV_ESC_RM_ALLOC_OBJECT                   _IOWR(NV_IOCTL_MAGIC, 40, char[20]) /* 0xc0144628 */
#define NV_ESC_RM_FREE                           _IOWR(NV_IOCTL_MAGIC, 41, char[16]) /* 0xc0104629 */
#define NV_ESC_RM_CONTROL                        _IOWR(NV_IOCTL_MAGIC, 42, char[32]) /* 0xc020462a */
#define NV_ESC_RM_ALLOC                          _IOWR(NV_IOCTL_MAGIC, 43, char[48]) /* 0xc030462b */
#define NV_ESC_RM_ALLOC_ALT                      _IOWR(NV_IOCTL_MAGIC, 43, char[32]) /* 0xc020462b */
#define NV_ESC_RM_DUP_OBJECT                     _IOWR(NV_IOCTL_MAGIC, 52, char[28]) /* 0xc01c4634 */
#define NV_ESC_RM_SHARE                          _IOWR(NV_IOCTL_MAGIC, 53, char[24]) /* 0xc0184635 */
#define NV_ESC_RM_I2C_ACCESS                     _IOWR(NV_IOCTL_MAGIC, 57, char[32]) /* 0xc0204639 */
#define NV_ESC_RM_IDLE_CHANNELS                  _IOWR(NV_IOCTL_MAGIC, 65, char[56]) /* 0xc0384641 */
#define NV_ESC_RM_VID_HEAP_CONTROL               _IOWR(NV_IOCTL_MAGIC, 74, char[184]) /* 0xc0b8464a */
#define NV_ESC_RM_ACCESS_REGISTRY                _IOWR(NV_IOCTL_MAGIC, 77, char[72]) /* 0xc048464d */
#define NV_ESC_RM_MAP_MEMORY                     _IOWR(NV_IOCTL_MAGIC, 78, char[56]) /* 0xc038464e */
#define NV_ESC_RM_UNMAP_MEMORY                   _IOWR(NV_IOCTL_MAGIC, 79, char[32]) /* 0xc020464f */
#define NV_ESC_RM_GET_EVENT_DATA                 _IOWR(NV_IOCTL_MAGIC, 82, char[16]) /* 0xc0104652 */
#define NV_ESC_RM_ALLOC_CONTEXT_DMA2             _IOWR(NV_IOCTL_MAGIC, 84, char[56]) /* 0xc0384654 */
#define NV_ESC_RM_MAP_MEMORY_DMA                 _IOWR(NV_IOCTL_MAGIC, 87, char[64]) /* 0xc0404657 */
#define NV_ESC_RM_UNMAP_MEMORY_DMA               _IOWR(NV_IOCTL_MAGIC, 88, char[48]) /* 0xc0304658 */
#define NV_ESC_RM_BIND_CONTEXT_DMA               _IOWR(NV_IOCTL_MAGIC, 89, char[16]) /* 0xc0104659 */
#define NV_ESC_RM_UPDATE_DEVICE_MAPPING_INFO     _IOWR(NV_IOCTL_MAGIC, 94, char[40]) /* 0xc028465e */
#define NV_ESC_RM_LOCKLESS_DIAGNOSTIC            _IOWR(NV_IOCTL_MAGIC, 95, char[15412]) /* 0xfc34465f */
#define NV_ESC_CARD_INFO                         _IOWR(NV_IOCTL_MAGIC, 200, char[72]) /* 0xc04846c8 */
#define NV_ESC_REGISTER_FD                       _IOWR(NV_IOCTL_MAGIC, 201, char[4]) /* 0xc00446c9 */
#define NV_ESC_ALLOC_OS_EVENT                    _IOWR(NV_IOCTL_MAGIC, 206, char[16]) /* 0xc01046ce */
#define NV_ESC_FREE_OS_EVENT                     _IOWR(NV_IOCTL_MAGIC, 207, char[16]) /* 0xc01046cf */
#define NV_ESC_STATUS_CODE                       _IOWR(NV_IOCTL_MAGIC, 209, char[12]) /* 0xc00c46d1 */
#define NV_ESC_CHECK_VERSION_STR                 _IOWR(NV_IOCTL_MAGIC, 210, char[72]) /* 0xc04846d2 */
#define NV_ESC_IOCTL_XFER_CMD                    _IOWR(NV_IOCTL_MAGIC, 211, char[16]) /* 0xc01046d3 */
#define NV_ESC_ATTACH_GPUS_TO_FD                 _IOWR(NV_IOCTL_MAGIC, 212, char[4]) /* 0xc00446d4 */
#define NV_ESC_QUERY_DEVICE_INTR                 _IOWR(NV_IOCTL_MAGIC, 213, char[8]) /* 0xc00846d5 */
#define NV_ESC_SYS_PARAMS                        _IOWR(NV_IOCTL_MAGIC, 214, char[8]) /* 0xc00846d6 */
#define NV_ESC_NUMA_INFO                         _IOWR(NV_IOCTL_MAGIC, 215, char[560]) /* 0xc23046d7 */
#define NV_ESC_SET_NUMA_STATUS                   _IOWR(NV_IOCTL_MAGIC, 216, char[4]) /* 0xc00446d8 */
#define NV_ESC_EXPORT_TO_DMABUF_FD               _IOWR(NV_IOCTL_MAGIC, 217, char[2608]) /* 0xca3046d9 */
#define NV_ESC_WAIT_OPEN_COMPLETE                _IOWR(NV_IOCTL_MAGIC, 218, char[8]) /* 0xc00846da */

/* /dev/nvidia-uvm */
#define UVM_REGISTER_GPU_VASPACE                 0x19
#define UVM_UNREGISTER_GPU_VASPACE               0x1a
#define UVM_REGISTER_CHANNEL                     0x1b
#define UVM_UNREGISTER_CHANNEL                   0x1c
#define UVM_ENABLE_PEER_ACCESS                   0x1d
#define UVM_DISABLE_PEER_ACCESS                  0x1e
#define UVM_MAP_EXTERNAL_ALLOCATION              0x21
#define UVM_FREE                                 0x22
#define UVM_REGISTER_GPU                         0x25
#define UVM_UNREGISTER_GPU                       0x26
#define UVM_PAGEABLE_MEM_ACCESS                  0x27
#define UVM_SET_PREFERRED_LOCATION               0x2a
#define UVM_UNSET_PREFERRED_LOCATION             0x2b
#define UVM_ENABLE_READ_DUPLICATION              0x2c
#define UVM_DISABLE_READ_DUPLICATION             0x2d
#define UVM_SET_ACCESSED_BY                      0x2e
#define UVM_UNSET_ACCESSED_BY                    0x2f
#define UVM_MIGRATE                              0x33
#define UVM_TOOLS_READ_PROCESS_MEMORY            0x3e
#define UVM_TOOLS_WRITE_PROCESS_MEMORY           0x3f
#define UVM_TOOLS_GET_PROCESSOR_UUID_TABLE       0x40
#define UVM_MAP_DYNAMIC_PARALLELISM_REGION       0x41
#define UVM_UNMAP_EXTERNAL                       0x42
#define UVM_TOOLS_FLUSH_EVENTS                   0x43
#define UVM_ALLOC_SEMAPHORE_POOL                 0x44
#define UVM_CLEAN_UP_ZOMBIE_RESOURCES            0x45
#define UVM_PAGEABLE_MEM_ACCESS_ON_GPU           0x46
#define UVM_POPULATE_PAGEABLE                    0x47
#define UVM_VALIDATE_VA_RANGE                    0x48
#define UVM_CREATE_EXTERNAL_RANGE                0x49
#define UVM_MAP_EXTERNAL_SPARSE                  0x4a
#define UVM_MM_INITIALIZE                        0x4b
#define UVM_TOOLS_GET_PROCESSOR_UUID_TABLE_V2    0x4d
#define UVM_ALLOC_DEVICE_P2P                     0x4e
#define UVM_CLEAR_ALL_ACCESS_COUNTERS            0x4f
#define UVM_DISCARD                              0x50
#define UVM_QUERY_RESIDENCY                      0x51
#define UVM_INITIALIZE                           0x30000001
#define UVM_DEINITIALIZE                         0x30000002

/* /dev/nvidia-uvm-tools */
#define UVM_TOOLS_INIT_EVENT_TRACKER             0x38
#define UVM_TOOLS_SET_NOTIFICATION_THRESHOLD     0x39
#define UVM_TOOLS_EVENT_QUEUE_ENABLE_EVENTS      0x3a
#define UVM_TOOLS_EVENT_QUEUE_DISABLE_EVENTS     0x3b
#define UVM_TOOLS_ENABLE_COUNTERS                0x3c
#define UVM_TOOLS_DISABLE_COUNTERS               0x3d
#define UVM_TOOLS_INIT_EVENT_TRACKER_V2          0x4c

/* /dev/nvidia-uvm */
#define UVM_TEST_GET_GPU_REF_COUNT               0xc8
#define UVM_TEST_RNG_SANITY                      0xc9
#define UVM_TEST_RANGE_TREE_DIRECTED             0xca
#define UVM_TEST_RANGE_TREE_RANDOM               0xcb
#define UVM_TEST_VA_RANGE_INFO                   0xcc
#define UVM_TEST_RM_MEM_SANITY                   0xcd
#define UVM_TEST_GPU_SEMAPHORE_SANITY            0xce
#define UVM_TEST_PEER_REF_COUNT                  0xcf
#define UVM_TEST_VA_RANGE_SPLIT                  0xd0
#define UVM_TEST_VA_RANGE_INJECT_SPLIT_ERROR     0xd1
#define UVM_TEST_PAGE_TREE                       0xd2
#define UVM_TEST_CHANGE_PTE_MAPPING              0xd3
#define UVM_TEST_TRACKER_SANITY                  0xd4
#define UVM_TEST_PUSH_SANITY                     0xd5
#define UVM_TEST_CHANNEL_SANITY                  0xd6
#define UVM_TEST_CHANNEL_STRESS                  0xd7
#define UVM_TEST_CE_SANITY                       0xd8
#define UVM_TEST_VA_BLOCK_INFO                   0xd9
#define UVM_TEST_LOCK_SANITY                     0xda
#define UVM_TEST_PERF_UTILS_SANITY               0xdb
#define UVM_TEST_KVMALLOC                        0xdc
#define UVM_TEST_PMM_QUERY                       0xdd
#define UVM_TEST_PMM_CHECK_LEAK                  0xde
#define UVM_TEST_PERF_EVENTS_SANITY              0xdf
#define UVM_TEST_PERF_MODULE_SANITY              0xe0
#define UVM_TEST_RANGE_ALLOCATOR_SANITY          0xe1
#define UVM_TEST_GET_RM_PTES                     0xe2
#define UVM_TEST_FAULT_BUFFER_FLUSH              0xe3
#define UVM_TEST_INJECT_TOOLS_EVENT              0xe4
#define UVM_TEST_INCREMENT_TOOLS_COUNTER         0xe5
#define UVM_TEST_MEM_SANITY                      0xe6
#define UVM_TEST_MAKE_CHANNEL_STOPS_IMMEDIATE    0xe8
#define UVM_TEST_VA_BLOCK_INJECT_ERROR           0xe9
#define UVM_TEST_PEER_IDENTITY_MAPPINGS          0xea
#define UVM_TEST_VA_RESIDENCY_INFO               0xeb
#define UVM_TEST_PMM_ASYNC_ALLOC                 0xec
#define UVM_TEST_SET_PREFETCH_FILTERING          0xed
#define UVM_TEST_PMM_SANITY                      0xf0
#define UVM_TEST_INVALIDATE_TLB                  0xf1
#define UVM_TEST_VA_BLOCK                        0xf2
#define UVM_TEST_EVICT_CHUNK                     0xf3
#define UVM_TEST_FLUSH_DEFERRED_WORK             0xf4
#define UVM_TEST_NV_KTHREAD_Q                    0xf5
#define UVM_TEST_SET_PAGE_PREFETCH_POLICY        0xf6
#define UVM_TEST_GET_PREFETCH_FAULTS_REENABLE_LAPSE 0xfa
#define UVM_TEST_SET_PREFETCH_FAULTS_REENABLE_LAPSE 0xfb
#define UVM_TEST_GET_KERNEL_VIRTUAL_ADDRESS      0xfc
#define UVM_TEST_PMA_ALLOC_FREE                  0xfd
#define UVM_TEST_PMM_ALLOC_FREE_ROOT             0xfe
#define UVM_TEST_PMM_INJECT_PMA_EVICT_ERROR      0xff
#define UVM_TEST_RECONFIGURE_ACCESS_COUNTERS     0x100
#define UVM_TEST_RESET_ACCESS_COUNTERS           0x101
#define UVM_TEST_SET_IGNORE_ACCESS_COUNTERS      0x102
#define UVM_TEST_CHECK_CHANNEL_VA_SPACE          0x103
#define UVM_TEST_ENABLE_STATIC_PEER_ACCESS       0x104
#define UVM_TEST_DISABLE_STATIC_PEER_ACCESS      0x105
#define UVM_TEST_GET_PAGE_THRASHING_POLICY       0x106
#define UVM_TEST_SET_PAGE_THRASHING_POLICY       0x107
#define UVM_TEST_VA_SPACE_MM_RETAIN              0x10b
#define UVM_TEST_PMM_CHUNK_WITH_ELEVATED_PAGE    0x10d
#define UVM_TEST_GET_GPU_TIME                    0x10e
#define UVM_TEST_ACCESS_COUNTERS_ENABLED_BY_DEFAULT 0x10f
#define UVM_TEST_VA_SPACE_INJECT_ERROR           0x110
#define UVM_TEST_PMM_RELEASE_FREE_ROOT_CHUNKS    0x111
#define UVM_TEST_DRAIN_REPLAYABLE_FAULTS         0x112
#define UVM_TEST_PMA_GET_BATCH_SIZE              0x113
#define UVM_TEST_PMM_QUERY_PMA_STATS             0x114
#define UVM_TEST_NUMA_CHECK_AFFINITY             0x116
#define UVM_TEST_VA_SPACE_ADD_DUMMY_THREAD_CONTEXTS 0x117
#define UVM_TEST_VA_SPACE_REMOVE_DUMMY_THREAD_CONTEXTS 0x118
#define UVM_TEST_THREAD_CONTEXT_SANITY           0x119
#define UVM_TEST_THREAD_CONTEXT_PERF             0x11a
#define UVM_TEST_GET_PAGEABLE_MEM_TYPE           0x11b
#define UVM_TEST_TOOLS_FLUSH_REPLAY_EVENTS       0x11c
#define UVM_TEST_REGISTER_UNLOAD_STATE_BUFFER    0x11d
#define UVM_TEST_RB_TREE_DIRECTED                0x11e
#define UVM_TEST_RB_TREE_RANDOM                  0x11f
#define UVM_TEST_HOST_SANITY                     0x120
#define UVM_TEST_VA_SPACE_MM_OR_CURRENT_RETAIN   0x121
#define UVM_TEST_GET_USER_SPACE_END_ADDRESS      0x122
#define UVM_TEST_GET_CPU_CHUNK_ALLOC_SIZES       0x123
#define UVM_TEST_VA_RANGE_INJECT_ADD_GPU_VA_SPACE_ERROR 0x125
#define UVM_TEST_DESTROY_GPU_VA_SPACE_DELAY      0x126
#define UVM_TEST_SEC2_SANITY                     0x127
#define UVM_TEST_CGROUP_ACCOUNTING_SUPPORTED     0x128
#define UVM_TEST_SPLIT_INVALIDATE_DELAY          0x12a
#define UVM_TEST_SEC2_CPU_GPU_ROUNDTRIP          0x12b
#define UVM_TEST_CPU_CHUNK_API                   0x12c
#define UVM_TEST_FORCE_CPU_TO_CPU_COPY_WITH_CE   0x12d
#define UVM_TEST_VA_SPACE_ALLOW_MOVABLE_ALLOCATIONS 0x12e
#define UVM_TEST_SKIP_MIGRATE_VMA                0x12f
#define UVM_TEST_INJECT_TOOLS_EVENT_V2           0x130
#define UVM_TEST_SET_P2P_SUSPENDED               0x131
#define UVM_TEST_INJECT_NVLINK_ERROR             0x132
#define UVM_TEST_FILE_INITIALIZE                 0x133
#define UVM_TEST_FILE_UNMAP                      0x134
#define UVM_TEST_QUERY_ACCESS_COUNTERS           0x135
#define UVM_TEST_VA_BLOCK_DISCARD_STATUS         0x136
#define UVM_TEST_PMM_GET_ALLOC_LIST              0x137
#define UVM_TEST_DUMP_ACCESS_BITS                0x138
#define UVM_TEST_DEAD_CHANNEL                    0x139
#define UVM_TEST_SET_NON_REPLAYABLE_DELAY        0x13a
#define UVM_TEST_DRAIN_ACCESS_COUNTERS           0x13b
#define UVM_TEST_QUERY_CDMM_DEVMEM               0x13c

#endif /* GSPWN_NVIDIA_IOCTL_H */